"""bulletproof_database_initial

Revision ID: b31d140f6e3c
Revises: 
Create Date: 2025-08-25 08:46:50.570283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31d140f6e3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_limits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('budget_type', sa.String(length=20), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('module_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('warning_threshold', sa.Float(), nullable=True),
    sa.Column('critical_threshold', sa.Float(), nullable=True),
    sa.Column('emergency_threshold', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('hard_limit', sa.Boolean(), nullable=True),
    sa.Column('current_usage', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_budget_enabled', 'budget_limits', ['enabled'], unique=False)
    op.create_index('idx_budget_type_provider', 'budget_limits', ['budget_type', 'provider'], unique=False)
    op.create_index(op.f('ix_budget_limits_budget_type'), 'budget_limits', ['budget_type'], unique=False)
    op.create_index(op.f('ix_budget_limits_model'), 'budget_limits', ['model'], unique=False)
    op.create_index(op.f('ix_budget_limits_module_name'), 'budget_limits', ['module_name'], unique=False)
    op.create_index(op.f('ix_budget_limits_provider'), 'budget_limits', ['provider'], unique=False)
    op.create_index(op.f('ix_budget_limits_user_id'), 'budget_limits', ['user_id'], unique=False)
    op.create_table('modules',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('module_version', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('license', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('owasp_categories', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('documentation_url', sa.String(length=2048), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('avg_execution_time', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_module_category', 'modules', ['category'], unique=False)
    op.create_index('idx_module_domain', 'modules', ['domain'], unique=False)
    op.create_index('idx_module_name', 'modules', ['name'], unique=False)
    op.create_index('idx_module_status', 'modules', ['status'], unique=False)
    op.create_table('payload_collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('maintainer', sa.String(length=100), nullable=True),
    sa.Column('license', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_path', sa.String(length=1024), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('total_payloads', sa.Integer(), nullable=True),
    sa.Column('active_payloads', sa.Integer(), nullable=True),
    sa.Column('avg_success_rate', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_collection_domain', 'payload_collections', ['domain'], unique=False)
    op.create_index('idx_collection_name', 'payload_collections', ['name'], unique=False)
    op.create_index('idx_collection_verified', 'payload_collections', ['verified'], unique=False)
    op.create_table('payload_effectiveness',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payload_id', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('payload_path', sa.String(length=512), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('total_uses', sa.Integer(), nullable=True),
    sa.Column('avg_confidence', sa.Integer(), nullable=True),
    sa.Column('effectiveness_rating', sa.String(length=20), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('technique_tags', sa.JSON(), nullable=True),
    sa.Column('target_environments', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_effectiveness_domain', 'payload_effectiveness', ['domain'], unique=False)
    op.create_index('idx_effectiveness_module', 'payload_effectiveness', ['module_name'], unique=False)
    op.create_index('idx_effectiveness_rating', 'payload_effectiveness', ['effectiveness_rating'], unique=False)
    op.create_index('idx_effectiveness_success_rate', 'payload_effectiveness', ['success_count', 'total_uses'], unique=False)
    op.create_table('payload_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('has_token', sa.Boolean(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('last_pulled', sa.DateTime(), nullable=True),
    sa.Column('auth_method', sa.String(length=20), nullable=True),
    sa.Column('clone_method', sa.String(length=20), nullable=True),
    sa.Column('last_commit_hash', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_source_enabled', 'payload_sources', ['enabled'], unique=False)
    op.create_index('idx_source_name', 'payload_sources', ['name'], unique=False)
    op.create_index('idx_source_priority', 'payload_sources', ['priority'], unique=False)
    op.create_table('targets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_type', sa.Enum('API', 'WEB_APPLICATION', 'CHATBOT', 'AI_SERVICE', 'MOBILE_APP', 'DESKTOP_APP', 'CLOUD_SERVICE', 'DATABASE', 'FILE_SYSTEM', 'CONTAINER', 'IOT_DEVICE', 'CUSTOM', name='targettype'), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', 'AZURE', 'AWS_BEDROCK', 'GOOGLE', 'HUGGINGFACE', 'OLLAMA', 'LITELLM', 'AUTO_DETECT', name='llmprovider'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', 'PENDING_VERIFICATION', 'VERIFICATION_FAILED', 'ACCESS_DENIED', 'RATE_LIMITED', 'UNREACHABLE', name='targetstatus'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('last_validated', sa.DateTime(), nullable=True),
    sa.Column('last_scanned', sa.DateTime(), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_target_name')
    )
    op.create_index('idx_target_enabled', 'targets', ['enabled'], unique=False)
    op.create_index('idx_target_name', 'targets', ['name'], unique=False)
    op.create_index('idx_target_status', 'targets', ['status'], unique=False)
    op.create_table('usage_aggregation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('module_name', sa.String(length=100), nullable=True),
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('successful_requests', sa.Integer(), nullable=True),
    sa.Column('failed_requests', sa.Integer(), nullable=True),
    sa.Column('total_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('total_completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cached_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('avg_cost_per_request', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('min_response_time', sa.Float(), nullable=True),
    sa.Column('max_response_time', sa.Float(), nullable=True),
    sa.Column('p95_response_time', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('fallback_rate', sa.Float(), nullable=True),
    sa.Column('avg_retry_count', sa.Float(), nullable=True),
    sa.Column('data_points', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aggregation_cost', 'usage_aggregation', ['total_cost'], unique=False)
    op.create_index('idx_aggregation_period', 'usage_aggregation', ['period', 'period_start'], unique=False)
    op.create_index('idx_aggregation_unique', 'usage_aggregation', ['period', 'period_start', 'provider', 'model', 'module_name', 'scan_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_usage_aggregation_model'), 'usage_aggregation', ['model'], unique=False)
    op.create_index(op.f('ix_usage_aggregation_module_name'), 'usage_aggregation', ['module_name'], unique=False)
    op.create_index(op.f('ix_usage_aggregation_period'), 'usage_aggregation', ['period'], unique=False)
    op.create_index(op.f('ix_usage_aggregation_period_end'), 'usage_aggregation', ['period_end'], unique=False)
    op.create_index(op.f('ix_usage_aggregation_period_start'), 'usage_aggregation', ['period_start'], unique=False)
    op.create_index(op.f('ix_usage_aggregation_provider'), 'usage_aggregation', ['provider'], unique=False)
    op.create_index(op.f('ix_usage_aggregation_scan_id'), 'usage_aggregation', ['scan_id'], unique=False)
    op.create_index(op.f('ix_usage_aggregation_user_id'), 'usage_aggregation', ['user_id'], unique=False)
    op.create_table('budget_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('budget_id', sa.String(length=36), nullable=False),
    sa.Column('alert_level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('current_usage', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('usage_percentage', sa.Float(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budget_limits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_alerts_alert_level'), 'budget_alerts', ['alert_level'], unique=False)
    op.create_index(op.f('ix_budget_alerts_budget_id'), 'budget_alerts', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budget_alerts_created_at'), 'budget_alerts', ['created_at'], unique=False)
    op.create_table('payloads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('payload_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('owasp_category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('license', sa.String(length=50), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('expected_indicators', sa.JSON(), nullable=True),
    sa.Column('failure_indicators', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('safe_for_production', sa.Boolean(), nullable=True),
    sa.Column('collection_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['payload_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payload_category', 'payloads', ['category'], unique=False)
    op.create_index('idx_payload_collection', 'payloads', ['collection_id'], unique=False)
    op.create_index('idx_payload_domain', 'payloads', ['domain'], unique=False)
    op.create_index('idx_payload_name', 'payloads', ['name'], unique=False)
    op.create_index('idx_payload_status', 'payloads', ['status'], unique=False)
    op.create_index('idx_payload_type', 'payloads', ['payload_type'], unique=False)
    op.create_table('scans',
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('modules_run', sa.Integer(), nullable=True),
    sa.Column('modules_failed', sa.Integer(), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scan_created', 'scans', ['created_at'], unique=False)
    op.create_index('idx_scan_started', 'scans', ['started_at'], unique=False)
    op.create_index('idx_scan_status', 'scans', ['status'], unique=False)
    op.create_index('idx_scan_target', 'scans', ['target_id'], unique=False)
    op.create_index('idx_scan_type', 'scans', ['scan_type'], unique=False)
    op.create_table('findings',
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('owasp_category', sa.String(length=50), nullable=True),
    sa.Column('attack_domain', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('false_positive_reason', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cwe_id', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_finding_domain', 'findings', ['attack_domain'], unique=False)
    op.create_index('idx_finding_module', 'findings', ['module'], unique=False)
    op.create_index('idx_finding_owasp', 'findings', ['owasp_category'], unique=False)
    op.create_index('idx_finding_scan', 'findings', ['scan_id'], unique=False)
    op.create_index('idx_finding_severity', 'findings', ['severity'], unique=False)
    op.create_index('idx_finding_status', 'findings', ['status'], unique=False)
    op.create_index('idx_finding_target', 'findings', ['target_id'], unique=False)
    op.create_table('module_results',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    op.create_index('idx_module_result_execution', 'module_results', ['execution_id'], unique=False)
    op.create_index('idx_module_result_module', 'module_results', ['module_id'], unique=False)
    op.create_index('idx_module_result_scan', 'module_results', ['scan_id'], unique=False)
    op.create_index('idx_module_result_started', 'module_results', ['started_at'], unique=False)
    op.create_index('idx_module_result_status', 'module_results', ['status'], unique=False)
    op.create_table('usage_tracking',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('module_name', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_tokens', sa.Integer(), nullable=True),
    sa.Column('prompt_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('completion_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('request_size', sa.Integer(), nullable=True),
    sa.Column('response_size', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_cost', 'usage_tracking', ['total_cost'], unique=False)
    op.create_index('idx_usage_created_at', 'usage_tracking', ['created_at'], unique=False)
    op.create_index('idx_usage_provider_model', 'usage_tracking', ['provider', 'model'], unique=False)
    op.create_index('idx_usage_scan_module', 'usage_tracking', ['scan_id', 'module_name'], unique=False)
    op.create_index('idx_usage_user_session', 'usage_tracking', ['user_id', 'session_id'], unique=False)
    op.create_index(op.f('ix_usage_tracking_created_at'), 'usage_tracking', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_tracking_model'), 'usage_tracking', ['model'], unique=False)
    op.create_index(op.f('ix_usage_tracking_module_name'), 'usage_tracking', ['module_name'], unique=False)
    op.create_index(op.f('ix_usage_tracking_provider'), 'usage_tracking', ['provider'], unique=False)
    op.create_index(op.f('ix_usage_tracking_request_id'), 'usage_tracking', ['request_id'], unique=False)
    op.create_index(op.f('ix_usage_tracking_scan_id'), 'usage_tracking', ['scan_id'], unique=False)
    op.create_index(op.f('ix_usage_tracking_session_id'), 'usage_tracking', ['session_id'], unique=False)
    op.create_index(op.f('ix_usage_tracking_user_id'), 'usage_tracking', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_tracking_user_id'), table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_session_id'), table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_scan_id'), table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_request_id'), table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_provider'), table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_module_name'), table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_model'), table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_created_at'), table_name='usage_tracking')
    op.drop_index('idx_usage_user_session', table_name='usage_tracking')
    op.drop_index('idx_usage_scan_module', table_name='usage_tracking')
    op.drop_index('idx_usage_provider_model', table_name='usage_tracking')
    op.drop_index('idx_usage_created_at', table_name='usage_tracking')
    op.drop_index('idx_usage_cost', table_name='usage_tracking')
    op.drop_table('usage_tracking')
    op.drop_index('idx_module_result_status', table_name='module_results')
    op.drop_index('idx_module_result_started', table_name='module_results')
    op.drop_index('idx_module_result_scan', table_name='module_results')
    op.drop_index('idx_module_result_module', table_name='module_results')
    op.drop_index('idx_module_result_execution', table_name='module_results')
    op.drop_table('module_results')
    op.drop_index('idx_finding_target', table_name='findings')
    op.drop_index('idx_finding_status', table_name='findings')
    op.drop_index('idx_finding_severity', table_name='findings')
    op.drop_index('idx_finding_scan', table_name='findings')
    op.drop_index('idx_finding_owasp', table_name='findings')
    op.drop_index('idx_finding_module', table_name='findings')
    op.drop_index('idx_finding_domain', table_name='findings')
    op.drop_table('findings')
    op.drop_index('idx_scan_type', table_name='scans')
    op.drop_index('idx_scan_target', table_name='scans')
    op.drop_index('idx_scan_status', table_name='scans')
    op.drop_index('idx_scan_started', table_name='scans')
    op.drop_index('idx_scan_created', table_name='scans')
    op.drop_table('scans')
    op.drop_index('idx_payload_type', table_name='payloads')
    op.drop_index('idx_payload_status', table_name='payloads')
    op.drop_index('idx_payload_name', table_name='payloads')
    op.drop_index('idx_payload_domain', table_name='payloads')
    op.drop_index('idx_payload_collection', table_name='payloads')
    op.drop_index('idx_payload_category', table_name='payloads')
    op.drop_table('payloads')
    op.drop_index(op.f('ix_budget_alerts_created_at'), table_name='budget_alerts')
    op.drop_index(op.f('ix_budget_alerts_budget_id'), table_name='budget_alerts')
    op.drop_index(op.f('ix_budget_alerts_alert_level'), table_name='budget_alerts')
    op.drop_table('budget_alerts')
    op.drop_index(op.f('ix_usage_aggregation_user_id'), table_name='usage_aggregation')
    op.drop_index(op.f('ix_usage_aggregation_scan_id'), table_name='usage_aggregation')
    op.drop_index(op.f('ix_usage_aggregation_provider'), table_name='usage_aggregation')
    op.drop_index(op.f('ix_usage_aggregation_period_start'), table_name='usage_aggregation')
    op.drop_index(op.f('ix_usage_aggregation_period_end'), table_name='usage_aggregation')
    op.drop_index(op.f('ix_usage_aggregation_period'), table_name='usage_aggregation')
    op.drop_index(op.f('ix_usage_aggregation_module_name'), table_name='usage_aggregation')
    op.drop_index(op.f('ix_usage_aggregation_model'), table_name='usage_aggregation')
    op.drop_index('idx_aggregation_unique', table_name='usage_aggregation')
    op.drop_index('idx_aggregation_period', table_name='usage_aggregation')
    op.drop_index('idx_aggregation_cost', table_name='usage_aggregation')
    op.drop_table('usage_aggregation')
    op.drop_index('idx_target_status', table_name='targets')
    op.drop_index('idx_target_name', table_name='targets')
    op.drop_index('idx_target_enabled', table_name='targets')
    op.drop_table('targets')
    op.drop_index('idx_source_priority', table_name='payload_sources')
    op.drop_index('idx_source_name', table_name='payload_sources')
    op.drop_index('idx_source_enabled', table_name='payload_sources')
    op.drop_table('payload_sources')
    op.drop_index('idx_effectiveness_success_rate', table_name='payload_effectiveness')
    op.drop_index('idx_effectiveness_rating', table_name='payload_effectiveness')
    op.drop_index('idx_effectiveness_module', table_name='payload_effectiveness')
    op.drop_index('idx_effectiveness_domain', table_name='payload_effectiveness')
    op.drop_table('payload_effectiveness')
    op.drop_index('idx_collection_verified', table_name='payload_collections')
    op.drop_index('idx_collection_name', table_name='payload_collections')
    op.drop_index('idx_collection_domain', table_name='payload_collections')
    op.drop_table('payload_collections')
    op.drop_index('idx_module_status', table_name='modules')
    op.drop_index('idx_module_name', table_name='modules')
    op.drop_index('idx_module_domain', table_name='modules')
    op.drop_index('idx_module_category', table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_budget_limits_user_id'), table_name='budget_limits')
    op.drop_index(op.f('ix_budget_limits_provider'), table_name='budget_limits')
    op.drop_index(op.f('ix_budget_limits_module_name'), table_name='budget_limits')
    op.drop_index(op.f('ix_budget_limits_model'), table_name='budget_limits')
    op.drop_index(op.f('ix_budget_limits_budget_type'), table_name='budget_limits')
    op.drop_index('idx_budget_type_provider', table_name='budget_limits')
    op.drop_index('idx_budget_enabled', table_name='budget_limits')
    op.drop_table('budget_limits')
    # ### end Alembic commands ###
