"""Initial consolidated database schema

Revision ID: c36b794df3bb
Revises: 
Create Date: 2025-08-24 18:35:03.334882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36b794df3bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('allowed_ips', sa.JSON(), nullable=True),
    sa.Column('allowed_domains', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('idx_api_key_expires', 'api_keys', ['expires_at'], unique=False)
    op.create_index('idx_api_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_key_prefix', 'api_keys', ['key_prefix'], unique=False)
    op.create_index('idx_api_key_revoked', 'api_keys', ['revoked'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('actor_details', sa.JSON(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('target_details', sa.JSON(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('action_result', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_audit_actor', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('idx_audit_correlation', 'audit_logs', ['correlation_id'], unique=False)
    op.create_index('idx_audit_event_id', 'audit_logs', ['event_id'], unique=False)
    op.create_index('idx_audit_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index('idx_audit_target', 'audit_logs', ['target_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('authentication_tokens',
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('claims', sa.JSON(), nullable=True),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('audience', sa.String(length=200), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revocation_reason', sa.String(length=200), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('ip_addresses', sa.JSON(), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=True),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_auth_token_entity', 'authentication_tokens', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_auth_token_expires', 'authentication_tokens', ['expires_at'], unique=False)
    op.create_index('idx_auth_token_hash', 'authentication_tokens', ['token_hash'], unique=False)
    op.create_index('idx_auth_token_refresh', 'authentication_tokens', ['refresh_token_hash'], unique=False)
    op.create_index('idx_auth_token_revoked', 'authentication_tokens', ['revoked'], unique=False)
    op.create_table('data_attack_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('poisoning_strategy', sa.String(length=50), nullable=True),
    sa.Column('attack_vector', sa.String(length=50), nullable=True),
    sa.Column('samples_poisoned', sa.Integer(), nullable=True),
    sa.Column('effectiveness_score', sa.Integer(), nullable=True),
    sa.Column('dataset_size', sa.Integer(), nullable=True),
    sa.Column('privacy_leakage_score', sa.Integer(), nullable=True),
    sa.Column('membership_accuracy', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_data_effectiveness', 'data_attack_stats', ['effectiveness_score'], unique=False)
    op.create_index('idx_data_module', 'data_attack_stats', ['module_name'], unique=False)
    op.create_index('idx_data_strategy', 'data_attack_stats', ['poisoning_strategy'], unique=False)
    op.create_table('migration_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('from_revision', sa.String(length=32), nullable=True),
    sa.Column('to_revision', sa.String(length=32), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('applied_by', sa.String(length=100), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('backup_id', sa.String(length=100), nullable=True),
    sa.Column('sql_executed', sa.Text(), nullable=True),
    sa.Column('audit_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_migration_audit_applied_at', 'migration_audit', ['applied_at'], unique=False)
    op.create_index('idx_migration_audit_revision', 'migration_audit', ['revision'], unique=False)
    op.create_index('idx_migration_audit_status', 'migration_audit', ['status'], unique=False)
    op.create_table('model_attack_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('fingerprinting_technique', sa.String(length=50), nullable=True),
    sa.Column('model_family_detected', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('extraction_success', sa.Boolean(), nullable=True),
    sa.Column('adversarial_examples_generated', sa.Integer(), nullable=True),
    sa.Column('architecture_hints', sa.JSON(), nullable=True),
    sa.Column('timing_characteristics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_confidence', 'model_attack_stats', ['confidence_score'], unique=False)
    op.create_index('idx_model_module', 'model_attack_stats', ['module_name'], unique=False)
    op.create_index('idx_model_technique', 'model_attack_stats', ['fingerprinting_technique'], unique=False)
    op.create_table('modules',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('license', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('owasp_categories', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('documentation_url', sa.String(length=2048), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_module_category', 'modules', ['category'], unique=False)
    op.create_index('idx_module_domain', 'modules', ['domain'], unique=False)
    op.create_index('idx_module_name', 'modules', ['name'], unique=False)
    op.create_index('idx_module_status', 'modules', ['status'], unique=False)
    op.create_table('oauth_providers',
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('authorization_url', sa.String(length=512), nullable=False),
    sa.Column('token_url', sa.String(length=512), nullable=False),
    sa.Column('userinfo_url', sa.String(length=512), nullable=True),
    sa.Column('revocation_url', sa.String(length=512), nullable=True),
    sa.Column('client_id', sa.String(length=200), nullable=False),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('response_type', sa.String(length=50), nullable=True),
    sa.Column('grant_types', sa.JSON(), nullable=True),
    sa.Column('token_endpoint_auth_method', sa.String(length=50), nullable=True),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('jwks_uri', sa.String(length=512), nullable=True),
    sa.Column('discovery_url', sa.String(length=512), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name')
    )
    op.create_index('idx_oauth_provider_enabled', 'oauth_providers', ['enabled'], unique=False)
    op.create_index('idx_oauth_provider_name', 'oauth_providers', ['provider_name'], unique=False)
    op.create_index('idx_oauth_provider_type', 'oauth_providers', ['provider_type'], unique=False)
    op.create_table('output_attack_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('attack_type', sa.String(length=50), nullable=True),
    sa.Column('encoding_method', sa.String(length=50), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('injection_success', sa.Boolean(), nullable=True),
    sa.Column('bypass_success', sa.Boolean(), nullable=True),
    sa.Column('steering_success', sa.Boolean(), nullable=True),
    sa.Column('detection_evasion_score', sa.Integer(), nullable=True),
    sa.Column('response_manipulation_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_output_module', 'output_attack_stats', ['module_name'], unique=False)
    op.create_index('idx_output_success', 'output_attack_stats', ['injection_success'], unique=False)
    op.create_index('idx_output_type', 'output_attack_stats', ['attack_type'], unique=False)
    op.create_table('payload_collections',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('maintainer', sa.String(length=100), nullable=True),
    sa.Column('license', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_path', sa.String(length=1024), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('total_payloads', sa.Integer(), nullable=True),
    sa.Column('active_payloads', sa.Integer(), nullable=True),
    sa.Column('avg_success_rate', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_collection_domain', 'payload_collections', ['domain'], unique=False)
    op.create_index('idx_collection_name', 'payload_collections', ['name'], unique=False)
    op.create_index('idx_collection_verified', 'payload_collections', ['verified'], unique=False)
    op.create_table('payload_effectiveness',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payload_id', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('payload_path', sa.String(length=512), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('total_uses', sa.Integer(), nullable=True),
    sa.Column('avg_confidence', sa.Integer(), nullable=True),
    sa.Column('effectiveness_rating', sa.String(length=20), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('technique_tags', sa.JSON(), nullable=True),
    sa.Column('target_environments', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_effectiveness_domain', 'payload_effectiveness', ['domain'], unique=False)
    op.create_index('idx_effectiveness_module', 'payload_effectiveness', ['module_name'], unique=False)
    op.create_index('idx_effectiveness_rating', 'payload_effectiveness', ['effectiveness_rating'], unique=False)
    op.create_index('idx_effectiveness_success_rate', 'payload_effectiveness', ['success_count', 'total_uses'], unique=False)
    op.create_table('payload_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('has_token', sa.Boolean(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('last_pulled', sa.DateTime(), nullable=True),
    sa.Column('auth_method', sa.String(length=20), nullable=True),
    sa.Column('clone_method', sa.String(length=20), nullable=True),
    sa.Column('last_commit_hash', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_source_enabled', 'payload_sources', ['enabled'], unique=False)
    op.create_index('idx_source_name', 'payload_sources', ['name'], unique=False)
    op.create_index('idx_source_priority', 'payload_sources', ['priority'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('operation_name', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('network_bytes', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('module_name', sa.String(length=100), nullable=True),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('metric_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_perf_module', 'performance_metrics', ['module_name'], unique=False)
    op.create_index('idx_perf_operation', 'performance_metrics', ['operation_name'], unique=False)
    op.create_index('idx_perf_scan', 'performance_metrics', ['scan_id'], unique=False)
    op.create_index('idx_perf_time', 'performance_metrics', ['start_time'], unique=False)
    op.create_index('idx_perf_type', 'performance_metrics', ['metric_type'], unique=False)
    op.create_table('prompt_attack_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('evasion_technique', sa.String(length=50), nullable=True),
    sa.Column('injection_type', sa.String(length=50), nullable=True),
    sa.Column('success_rate', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('indicators_found', sa.JSON(), nullable=True),
    sa.Column('extracted_content', sa.Text(), nullable=True),
    sa.Column('technique_effectiveness', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prompt_module', 'prompt_attack_stats', ['module_name'], unique=False)
    op.create_index('idx_prompt_success', 'prompt_attack_stats', ['success_rate'], unique=False)
    op.create_index('idx_prompt_technique', 'prompt_attack_stats', ['evasion_technique'], unique=False)
    op.create_table('prompt_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('has_token', sa.Boolean(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('last_pulled', sa.DateTime(), nullable=True),
    sa.Column('auth_method', sa.String(length=20), nullable=True),
    sa.Column('clone_method', sa.String(length=20), nullable=True),
    sa.Column('last_commit_hash', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('report_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('required_data', sa.JSON(), nullable=True),
    sa.Column('style_config', sa.JSON(), nullable=True),
    sa.Column('logo_path', sa.String(length=512), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_modified_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_template_enabled', 'report_templates', ['enabled'], unique=False)
    op.create_index('idx_template_name', 'report_templates', ['name'], unique=False)
    op.create_index('idx_template_type', 'report_templates', ['template_type'], unique=False)
    op.create_table('reports',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('generation_started', sa.DateTime(), nullable=True),
    sa.Column('generation_completed', sa.DateTime(), nullable=True),
    sa.Column('generation_duration', sa.Float(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('scan_ids', sa.JSON(), nullable=True),
    sa.Column('target_ids', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_created', 'reports', ['created_at'], unique=False)
    op.create_index('idx_report_generated_by', 'reports', ['generated_by'], unique=False)
    op.create_index('idx_report_status', 'reports', ['status'], unique=False)
    op.create_index('idx_report_type', 'reports', ['report_type'], unique=False)
    op.create_table('security_event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_class', sa.String(length=50), nullable=False),
    sa.Column('threat_level', sa.String(length=20), nullable=False),
    sa.Column('attack_pattern', sa.String(length=100), nullable=True),
    sa.Column('detection_method', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('false_positive_probability', sa.Float(), nullable=True),
    sa.Column('data_affected', sa.Boolean(), nullable=True),
    sa.Column('systems_affected', sa.JSON(), nullable=True),
    sa.Column('potential_damage', sa.String(length=50), nullable=True),
    sa.Column('response_action', sa.String(length=100), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('mitigation_applied', sa.Boolean(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('source_country', sa.String(length=2), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_security_class', 'security_event_logs', ['event_class'], unique=False)
    op.create_index('idx_security_event_id', 'security_event_logs', ['event_id'], unique=False)
    op.create_index('idx_security_pattern', 'security_event_logs', ['attack_pattern'], unique=False)
    op.create_index('idx_security_threat', 'security_event_logs', ['threat_level'], unique=False)
    op.create_index('idx_security_timestamp', 'security_event_logs', ['timestamp'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('terminated', sa.Boolean(), nullable=True),
    sa.Column('termination_reason', sa.String(length=200), nullable=True),
    sa.Column('csrf_token', sa.String(length=128), nullable=True),
    sa.Column('is_secure', sa.Boolean(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_session_expires', 'sessions', ['expires_at'], unique=False)
    op.create_index('idx_session_id', 'sessions', ['session_id'], unique=False)
    op.create_index('idx_session_last_activity', 'sessions', ['last_activity'], unique=False)
    op.create_index('idx_session_terminated', 'sessions', ['terminated'], unique=False)
    op.create_index('idx_session_user', 'sessions', ['user_id'], unique=False)
    op.create_table('system_attack_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('enumeration_method', sa.String(length=50), nullable=True),
    sa.Column('attack_type', sa.String(length=50), nullable=True),
    sa.Column('open_ports_found', sa.Integer(), nullable=True),
    sa.Column('services_detected', sa.Integer(), nullable=True),
    sa.Column('vulnerabilities_found', sa.Integer(), nullable=True),
    sa.Column('privilege_escalation_success', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('enumeration_depth', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_method', 'system_attack_stats', ['enumeration_method'], unique=False)
    op.create_index('idx_system_module', 'system_attack_stats', ['module_name'], unique=False)
    op.create_index('idx_system_risk', 'system_attack_stats', ['risk_score'], unique=False)
    op.create_table('targets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('authentication', sa.JSON(), nullable=True),
    sa.Column('endpoints', sa.JSON(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=True),
    sa.Column('finding_count', sa.Integer(), nullable=True),
    sa.Column('last_scanned', sa.DateTime(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('verification_interval', sa.Integer(), nullable=True),
    sa.Column('compliance_requirements', sa.JSON(), nullable=True),
    sa.Column('data_classification', sa.String(length=50), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_target_environment', 'targets', ['environment'], unique=False)
    op.create_index('idx_target_name', 'targets', ['name'], unique=False)
    op.create_index('idx_target_status', 'targets', ['status'], unique=False)
    op.create_index('idx_target_type', 'targets', ['target_type'], unique=False)
    op.create_table('encrypted_credentials',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=64), nullable=False),
    sa.Column('encryption_algorithm', sa.String(length=32), nullable=False),
    sa.Column('credential_type', sa.String(length=32), nullable=False),
    sa.Column('key_format', sa.String(length=32), nullable=False),
    sa.Column('masked_preview', sa.String(length=16), nullable=True),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=32), nullable=True),
    sa.Column('validation_endpoint', sa.String(length=512), nullable=True),
    sa.Column('rate_limit_info', sa.JSON(), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=True),
    sa.Column('environment_variable', sa.String(length=128), nullable=True),
    sa.Column('vault_path', sa.String(length=256), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('access_log', sa.JSON(), nullable=True),
    sa.Column('rotation_history', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credentials_encryption_key', 'encrypted_credentials', ['encryption_key_id'], unique=False)
    op.create_index('idx_credentials_environment', 'encrypted_credentials', ['environment'], unique=False)
    op.create_index('idx_credentials_last_used', 'encrypted_credentials', ['last_used_at'], unique=False)
    op.create_index('idx_credentials_provider', 'encrypted_credentials', ['provider_name'], unique=False)
    op.create_index('idx_credentials_status', 'encrypted_credentials', ['validation_status'], unique=False)
    op.create_index('idx_credentials_target_id', 'encrypted_credentials', ['target_id'], unique=False)
    op.create_index('idx_credentials_target_provider', 'encrypted_credentials', ['target_id', 'provider_name'], unique=False)
    op.create_table('payloads',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('payload_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('owasp_category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('license', sa.String(length=50), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('expected_indicators', sa.JSON(), nullable=True),
    sa.Column('failure_indicators', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('safe_for_production', sa.Boolean(), nullable=True),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['payload_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payload_category', 'payloads', ['category'], unique=False)
    op.create_index('idx_payload_collection', 'payloads', ['collection_id'], unique=False)
    op.create_index('idx_payload_domain', 'payloads', ['domain'], unique=False)
    op.create_index('idx_payload_name', 'payloads', ['name'], unique=False)
    op.create_index('idx_payload_status', 'payloads', ['status'], unique=False)
    op.create_index('idx_payload_type', 'payloads', ['payload_type'], unique=False)
    op.create_table('prompt_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('prompt_count', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('cache_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['prompt_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_category', 'prompt_collections', ['source_id', 'category'], unique=True)
    op.create_table('report_distributions',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('distribution_type', sa.String(length=50), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('encryption_enabled', sa.Boolean(), nullable=True),
    sa.Column('password_protected', sa.Boolean(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('access_token', sa.String(length=128), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('error_messages', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_distribution_report', 'report_distributions', ['report_id'], unique=False)
    op.create_index('idx_distribution_sent', 'report_distributions', ['sent_at'], unique=False)
    op.create_index('idx_distribution_status', 'report_distributions', ['status'], unique=False)
    op.create_table('report_schedules',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('report_config', sa.JSON(), nullable=False),
    sa.Column('target_ids', sa.JSON(), nullable=True),
    sa.Column('target_tags', sa.JSON(), nullable=True),
    sa.Column('scan_age_days', sa.Integer(), nullable=True),
    sa.Column('distribution_config', sa.JSON(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_schedule_enabled', 'report_schedules', ['enabled'], unique=False)
    op.create_index('idx_schedule_name', 'report_schedules', ['name'], unique=False)
    op.create_index('idx_schedule_next_run', 'report_schedules', ['next_run'], unique=False)
    op.create_table('scans',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('modules_run', sa.Integer(), nullable=True),
    sa.Column('modules_failed', sa.Integer(), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scan_created', 'scans', ['created_at'], unique=False)
    op.create_index('idx_scan_started', 'scans', ['started_at'], unique=False)
    op.create_index('idx_scan_status', 'scans', ['status'], unique=False)
    op.create_index('idx_scan_target', 'scans', ['target_id'], unique=False)
    op.create_index('idx_scan_type', 'scans', ['scan_type'], unique=False)
    op.create_table('findings',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('owasp_category', sa.String(length=50), nullable=True),
    sa.Column('attack_domain', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('false_positive_reason', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cwe_id', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_finding_domain', 'findings', ['attack_domain'], unique=False)
    op.create_index('idx_finding_module', 'findings', ['module'], unique=False)
    op.create_index('idx_finding_owasp', 'findings', ['owasp_category'], unique=False)
    op.create_index('idx_finding_scan', 'findings', ['scan_id'], unique=False)
    op.create_index('idx_finding_severity', 'findings', ['severity'], unique=False)
    op.create_index('idx_finding_status', 'findings', ['status'], unique=False)
    op.create_index('idx_finding_target', 'findings', ['target_id'], unique=False)
    op.create_table('module_results',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    op.create_index('idx_module_result_execution', 'module_results', ['execution_id'], unique=False)
    op.create_index('idx_module_result_module', 'module_results', ['module_id'], unique=False)
    op.create_index('idx_module_result_scan', 'module_results', ['scan_id'], unique=False)
    op.create_index('idx_module_result_started', 'module_results', ['started_at'], unique=False)
    op.create_index('idx_module_result_status', 'module_results', ['status'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('attack_type', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('prompt_metadata', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['prompt_collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index('idx_prompt_category', 'prompts', ['category'], unique=False)
    op.create_index('idx_prompt_hash', 'prompts', ['hash'], unique=False)
    op.create_index('idx_prompt_severity', 'prompts', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prompt_severity', table_name='prompts')
    op.drop_index('idx_prompt_hash', table_name='prompts')
    op.drop_index('idx_prompt_category', table_name='prompts')
    op.drop_table('prompts')
    op.drop_index('idx_module_result_status', table_name='module_results')
    op.drop_index('idx_module_result_started', table_name='module_results')
    op.drop_index('idx_module_result_scan', table_name='module_results')
    op.drop_index('idx_module_result_module', table_name='module_results')
    op.drop_index('idx_module_result_execution', table_name='module_results')
    op.drop_table('module_results')
    op.drop_index('idx_finding_target', table_name='findings')
    op.drop_index('idx_finding_status', table_name='findings')
    op.drop_index('idx_finding_severity', table_name='findings')
    op.drop_index('idx_finding_scan', table_name='findings')
    op.drop_index('idx_finding_owasp', table_name='findings')
    op.drop_index('idx_finding_module', table_name='findings')
    op.drop_index('idx_finding_domain', table_name='findings')
    op.drop_table('findings')
    op.drop_index('idx_scan_type', table_name='scans')
    op.drop_index('idx_scan_target', table_name='scans')
    op.drop_index('idx_scan_status', table_name='scans')
    op.drop_index('idx_scan_started', table_name='scans')
    op.drop_index('idx_scan_created', table_name='scans')
    op.drop_table('scans')
    op.drop_index('idx_schedule_next_run', table_name='report_schedules')
    op.drop_index('idx_schedule_name', table_name='report_schedules')
    op.drop_index('idx_schedule_enabled', table_name='report_schedules')
    op.drop_table('report_schedules')
    op.drop_index('idx_distribution_status', table_name='report_distributions')
    op.drop_index('idx_distribution_sent', table_name='report_distributions')
    op.drop_index('idx_distribution_report', table_name='report_distributions')
    op.drop_table('report_distributions')
    op.drop_index('idx_source_category', table_name='prompt_collections')
    op.drop_table('prompt_collections')
    op.drop_index('idx_payload_type', table_name='payloads')
    op.drop_index('idx_payload_status', table_name='payloads')
    op.drop_index('idx_payload_name', table_name='payloads')
    op.drop_index('idx_payload_domain', table_name='payloads')
    op.drop_index('idx_payload_collection', table_name='payloads')
    op.drop_index('idx_payload_category', table_name='payloads')
    op.drop_table('payloads')
    op.drop_index('idx_credentials_target_provider', table_name='encrypted_credentials')
    op.drop_index('idx_credentials_target_id', table_name='encrypted_credentials')
    op.drop_index('idx_credentials_status', table_name='encrypted_credentials')
    op.drop_index('idx_credentials_provider', table_name='encrypted_credentials')
    op.drop_index('idx_credentials_last_used', table_name='encrypted_credentials')
    op.drop_index('idx_credentials_environment', table_name='encrypted_credentials')
    op.drop_index('idx_credentials_encryption_key', table_name='encrypted_credentials')
    op.drop_table('encrypted_credentials')
    op.drop_index('idx_target_type', table_name='targets')
    op.drop_index('idx_target_status', table_name='targets')
    op.drop_index('idx_target_name', table_name='targets')
    op.drop_index('idx_target_environment', table_name='targets')
    op.drop_table('targets')
    op.drop_index('idx_system_risk', table_name='system_attack_stats')
    op.drop_index('idx_system_module', table_name='system_attack_stats')
    op.drop_index('idx_system_method', table_name='system_attack_stats')
    op.drop_table('system_attack_stats')
    op.drop_index('idx_session_user', table_name='sessions')
    op.drop_index('idx_session_terminated', table_name='sessions')
    op.drop_index('idx_session_last_activity', table_name='sessions')
    op.drop_index('idx_session_id', table_name='sessions')
    op.drop_index('idx_session_expires', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_security_timestamp', table_name='security_event_logs')
    op.drop_index('idx_security_threat', table_name='security_event_logs')
    op.drop_index('idx_security_pattern', table_name='security_event_logs')
    op.drop_index('idx_security_event_id', table_name='security_event_logs')
    op.drop_index('idx_security_class', table_name='security_event_logs')
    op.drop_table('security_event_logs')
    op.drop_index('idx_report_type', table_name='reports')
    op.drop_index('idx_report_status', table_name='reports')
    op.drop_index('idx_report_generated_by', table_name='reports')
    op.drop_index('idx_report_created', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_template_type', table_name='report_templates')
    op.drop_index('idx_template_name', table_name='report_templates')
    op.drop_index('idx_template_enabled', table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_table('prompt_sources')
    op.drop_index('idx_prompt_technique', table_name='prompt_attack_stats')
    op.drop_index('idx_prompt_success', table_name='prompt_attack_stats')
    op.drop_index('idx_prompt_module', table_name='prompt_attack_stats')
    op.drop_table('prompt_attack_stats')
    op.drop_index('idx_perf_type', table_name='performance_metrics')
    op.drop_index('idx_perf_time', table_name='performance_metrics')
    op.drop_index('idx_perf_scan', table_name='performance_metrics')
    op.drop_index('idx_perf_operation', table_name='performance_metrics')
    op.drop_index('idx_perf_module', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index('idx_source_priority', table_name='payload_sources')
    op.drop_index('idx_source_name', table_name='payload_sources')
    op.drop_index('idx_source_enabled', table_name='payload_sources')
    op.drop_table('payload_sources')
    op.drop_index('idx_effectiveness_success_rate', table_name='payload_effectiveness')
    op.drop_index('idx_effectiveness_rating', table_name='payload_effectiveness')
    op.drop_index('idx_effectiveness_module', table_name='payload_effectiveness')
    op.drop_index('idx_effectiveness_domain', table_name='payload_effectiveness')
    op.drop_table('payload_effectiveness')
    op.drop_index('idx_collection_verified', table_name='payload_collections')
    op.drop_index('idx_collection_name', table_name='payload_collections')
    op.drop_index('idx_collection_domain', table_name='payload_collections')
    op.drop_table('payload_collections')
    op.drop_index('idx_output_type', table_name='output_attack_stats')
    op.drop_index('idx_output_success', table_name='output_attack_stats')
    op.drop_index('idx_output_module', table_name='output_attack_stats')
    op.drop_table('output_attack_stats')
    op.drop_index('idx_oauth_provider_type', table_name='oauth_providers')
    op.drop_index('idx_oauth_provider_name', table_name='oauth_providers')
    op.drop_index('idx_oauth_provider_enabled', table_name='oauth_providers')
    op.drop_table('oauth_providers')
    op.drop_index('idx_module_status', table_name='modules')
    op.drop_index('idx_module_name', table_name='modules')
    op.drop_index('idx_module_domain', table_name='modules')
    op.drop_index('idx_module_category', table_name='modules')
    op.drop_table('modules')
    op.drop_index('idx_model_technique', table_name='model_attack_stats')
    op.drop_index('idx_model_module', table_name='model_attack_stats')
    op.drop_index('idx_model_confidence', table_name='model_attack_stats')
    op.drop_table('model_attack_stats')
    op.drop_index('idx_migration_audit_status', table_name='migration_audit')
    op.drop_index('idx_migration_audit_revision', table_name='migration_audit')
    op.drop_index('idx_migration_audit_applied_at', table_name='migration_audit')
    op.drop_table('migration_audit')
    op.drop_index('idx_data_strategy', table_name='data_attack_stats')
    op.drop_index('idx_data_module', table_name='data_attack_stats')
    op.drop_index('idx_data_effectiveness', table_name='data_attack_stats')
    op.drop_table('data_attack_stats')
    op.drop_index('idx_auth_token_revoked', table_name='authentication_tokens')
    op.drop_index('idx_auth_token_refresh', table_name='authentication_tokens')
    op.drop_index('idx_auth_token_hash', table_name='authentication_tokens')
    op.drop_index('idx_auth_token_expires', table_name='authentication_tokens')
    op.drop_index('idx_auth_token_entity', table_name='authentication_tokens')
    op.drop_table('authentication_tokens')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_target', table_name='audit_logs')
    op.drop_index('idx_audit_event_type', table_name='audit_logs')
    op.drop_index('idx_audit_event_id', table_name='audit_logs')
    op.drop_index('idx_audit_correlation', table_name='audit_logs')
    op.drop_index('idx_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_api_key_revoked', table_name='api_keys')
    op.drop_index('idx_api_key_prefix', table_name='api_keys')
    op.drop_index('idx_api_key_hash', table_name='api_keys')
    op.drop_index('idx_api_key_expires', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
